name: Semver Workflow

on:
  push:
    branches: [main]

permissions:
  deployments: write
  contents: write
  actions: write

jobs:
    Semver:
       runs-on: ubuntu-latest
    env:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup semver bash
        if: github.event.pull_request.merged
        run: |
          sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/3.0.0/src/semver -o /usr/local/bin/semver && sudo chmod +x /usr/local/bin/semver
          semver --version
      - name: Get version
        id: get-version
        if: github.event.pull_request.merged
        run: |
          git fetch --tags
          last_version=$(git tag --sort=-version:refname | grep -P "^$package_name@v\d+.\d+.\d+$" | head -n 1 | cut -d v -f 2)
          if [ -z "$last_version" ]; then
            new_version=1.0.0
          elif [[ "${{ github.event.pull_request.title }}" =~ ^"major" ]]; then
            new_version=$(semver bump major "$last_version")
          elif [[ "${{ github.event.pull_request.title }}" =~ ^"feat" ]]; then
            new_version=$(semver bump minor "$last_version")
          else
            new_version=$(semver bump patch "$last_version")
          fi
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
      - name: Prepare tag
        id: prepare
        if: github.event.pull_request.merged
        run: |
          VERSION=v${RELEASE_VERSION}
          echo "tag_version=$VERSION" >> $GITHUB_ENV

      - name: Push Tag
        if: github.event.pull_request.merged
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          custom_tag: ${{ env.tag_version }}
          tag_prefix: ""
      - name: Create release
        if: github.event.pull_request.merged
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          prerelease: false
          title: ${{ env.tag_version }}
          automatic_release_tag: ${{ env.tag_version }}
          
